#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /profil/register
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
